In [1]:
import numpy as np

In [2]:
#Create an array
a = np.array([5,2,7,4,1])
a

array([5, 2, 7, 4, 1])

In [3]:
print(a)

[5 2 7 4 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
#Creation of multiple dimensional array or a matrix
v = np.array([[5,2,7],[4,1,8],[11,17,25]])
v

array([[ 5,  2,  7],
       [ 4,  1,  8],
       [11, 17, 25]])

In [6]:
print(v)

[[ 5  2  7]
 [ 4  1  8]
 [11 17 25]]


In [7]:
v.shape #To check the rows & columns of a matrix

(3, 3)

In [8]:
v1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
v1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
v1.shape

(3, 3)

In [10]:
v

array([[ 5,  2,  7],
       [ 4,  1,  8],
       [11, 17, 25]])

In [11]:
#Matrix Multiplication
a = np.matmul(v1,v)
a

array([[ 46,  55,  98],
       [106, 115, 218],
       [166, 175, 338]])

In [12]:
v1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#Alternative method for matmul
b = np.dot(v,v1)

In [14]:
b

array([[ 62,  76,  90],
       [ 64,  77,  90],
       [254, 307, 360]])

In [15]:
#sum
s = np.add(v,v1)

In [16]:
s

array([[ 6,  4, 10],
       [ 8,  6, 14],
       [18, 25, 34]])

In [17]:
div = np.divide(v,v1)

In [18]:
div

array([[5.        , 1.        , 2.33333333],
       [1.        , 0.2       , 1.33333333],
       [1.57142857, 2.125     , 2.77777778]])

In [19]:
v

array([[ 5,  2,  7],
       [ 4,  1,  8],
       [11, 17, 25]])

In [20]:
v1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
#linear multiplication in numpy
m = np.multiply(v,v1)

In [22]:
m

array([[  5,   4,  21],
       [ 16,   5,  48],
       [ 77, 136, 225]])

In [23]:
#subtract 
sub = np.subtract(v,v1)

In [24]:
sub

array([[ 4,  0,  4],
       [ 0, -4,  2],
       [ 4,  9, 16]])